site_name: AutoMTL
theme:
  name: material
nav:
  - Home: index.md
  - Example:
      - mobilenetv2: mobilenetv2.md
  - Documentation:
      - Node: layer_node.md
      - Multi-task Model (parent class): mtl_model.md
